/**
 * Song database for range-matched suggestions.
 *
 * Each entry: { title, artist, midiLow, midiHigh, genre, difficulty }
 *   difficulty: 1 = beginner-friendly, 2 = intermediate, 3 = advanced
 *
 * Ranges represent the *melody* range a singer needs to cover,
 * not the full orchestral arrangement.
 *
 * Sources: vocal range databases, sheet music, transcription analysis.
 * Erring on the side of the "standard" or most-covered version.
 */

const SONG_DATABASE = [
  // ── BASS / LOW BARITONE (bottom ~E2–D4) ─────────────────────────────────
  { title: "Ring of Fire", artist: "Johnny Cash", midiLow: 43, midiHigh: 60, genre: "Country", difficulty: 1 },
  { title: "Folsom Prison Blues", artist: "Johnny Cash", midiLow: 43, midiHigh: 59, genre: "Country", difficulty: 1 },
  { title: "Sixteen Tons", artist: "Tennessee Ernie Ford", midiLow: 40, midiHigh: 58, genre: "Folk", difficulty: 1 },
  { title: "Old Man River", artist: "Paul Robeson", midiLow: 39, midiHigh: 57, genre: "Musical Theater", difficulty: 2 },
  { title: "Can't Help Falling in Love", artist: "Elvis Presley", midiLow: 47, midiHigh: 64, genre: "Pop", difficulty: 1 },
  { title: "Sound of Silence", artist: "Simon & Garfunkel", midiLow: 45, midiHigh: 62, genre: "Folk", difficulty: 1 },
  { title: "Hurt", artist: "Johnny Cash", midiLow: 43, midiHigh: 60, genre: "Alternative", difficulty: 1 },
  { title: "The Man in Black", artist: "Johnny Cash", midiLow: 43, midiHigh: 58, genre: "Country", difficulty: 1 },
  { title: "In the Ghetto", artist: "Elvis Presley", midiLow: 45, midiHigh: 62, genre: "Pop", difficulty: 1 },
  { title: "Suspicious Minds", artist: "Elvis Presley", midiLow: 46, midiHigh: 64, genre: "Pop", difficulty: 2 },

  // ── BARITONE (bottom ~G2–G4) ────────────────────────────────────────────
  { title: "Hallelujah", artist: "Leonard Cohen", midiLow: 45, midiHigh: 62, genre: "Folk", difficulty: 1 },
  { title: "Stand By Me", artist: "Ben E. King", midiLow: 47, midiHigh: 62, genre: "Soul", difficulty: 1 },
  { title: "House of the Rising Sun", artist: "The Animals", midiLow: 45, midiHigh: 65, genre: "Rock", difficulty: 2 },
  { title: "Knockin' on Heaven's Door", artist: "Bob Dylan", midiLow: 47, midiHigh: 62, genre: "Rock", difficulty: 1 },
  { title: "Wish You Were Here", artist: "Pink Floyd", midiLow: 48, midiHigh: 64, genre: "Rock", difficulty: 1 },
  { title: "Let It Be", artist: "The Beatles", midiLow: 48, midiHigh: 65, genre: "Rock", difficulty: 1 },
  { title: "Hey Jude", artist: "The Beatles", midiLow: 50, midiHigh: 67, genre: "Rock", difficulty: 1 },
  { title: "Yesterday", artist: "The Beatles", midiLow: 52, midiHigh: 67, genre: "Pop", difficulty: 1 },
  { title: "Hotel California", artist: "Eagles", midiLow: 50, midiHigh: 67, genre: "Rock", difficulty: 2 },
  { title: "Wonderwall", artist: "Oasis", midiLow: 50, midiHigh: 66, genre: "Rock", difficulty: 1 },
  { title: "Unchained Melody", artist: "The Righteous Brothers", midiLow: 47, midiHigh: 67, genre: "Pop", difficulty: 2 },
  { title: "Moon River", artist: "Andy Williams", midiLow: 48, midiHigh: 64, genre: "Jazz", difficulty: 1 },
  { title: "Georgia on My Mind", artist: "Ray Charles", midiLow: 47, midiHigh: 64, genre: "Jazz", difficulty: 2 },
  { title: "Feeling Good", artist: "Nina Simone", midiLow: 48, midiHigh: 65, genre: "Jazz", difficulty: 2 },
  { title: "Dream a Little Dream", artist: "Mama Cass", midiLow: 50, midiHigh: 64, genre: "Pop", difficulty: 1 },
  { title: "Bridge Over Troubled Water", artist: "Simon & Garfunkel", midiLow: 48, midiHigh: 67, genre: "Pop", difficulty: 2 },
  { title: "The Boxer", artist: "Simon & Garfunkel", midiLow: 48, midiHigh: 64, genre: "Folk", difficulty: 1 },
  { title: "Fast Car", artist: "Tracy Chapman", midiLow: 49, midiHigh: 66, genre: "Folk", difficulty: 1 },
  { title: "Budapest", artist: "George Ezra", midiLow: 46, midiHigh: 62, genre: "Pop", difficulty: 1 },
  { title: "Shotgun", artist: "George Ezra", midiLow: 46, midiHigh: 64, genre: "Pop", difficulty: 1 },
  { title: "Ho Hey", artist: "The Lumineers", midiLow: 48, midiHigh: 64, genre: "Folk", difficulty: 1 },
  { title: "Riptide", artist: "Vance Joy", midiLow: 50, midiHigh: 67, genre: "Pop", difficulty: 1 },
  { title: "Count on Me", artist: "Bruno Mars", midiLow: 52, midiHigh: 66, genre: "Pop", difficulty: 1 },
  { title: "I'm Yours", artist: "Jason Mraz", midiLow: 50, midiHigh: 67, genre: "Pop", difficulty: 1 },
  { title: "Three Little Birds", artist: "Bob Marley", midiLow: 50, midiHigh: 64, genre: "Reggae", difficulty: 1 },
  { title: "Redemption Song", artist: "Bob Marley", midiLow: 48, midiHigh: 64, genre: "Reggae", difficulty: 1 },
  { title: "What a Wonderful World", artist: "Louis Armstrong", midiLow: 46, midiHigh: 62, genre: "Jazz", difficulty: 1 },
  { title: "Fly Me to the Moon", artist: "Frank Sinatra", midiLow: 48, midiHigh: 64, genre: "Jazz", difficulty: 1 },
  { title: "My Way", artist: "Frank Sinatra", midiLow: 47, midiHigh: 65, genre: "Pop", difficulty: 2 },
  { title: "Come Together", artist: "The Beatles", midiLow: 48, midiHigh: 62, genre: "Rock", difficulty: 1 },
  { title: "Blackbird", artist: "The Beatles", midiLow: 52, midiHigh: 67, genre: "Folk", difficulty: 2 },

  // ── TENOR (bottom ~C3–C5) ───────────────────────────────────────────────
  { title: "Perfect", artist: "Ed Sheeran", midiLow: 47, midiHigh: 67, genre: "Pop", difficulty: 1 },
  { title: "Thinking Out Loud", artist: "Ed Sheeran", midiLow: 50, midiHigh: 69, genre: "Pop", difficulty: 2 },
  { title: "Shape of You", artist: "Ed Sheeran", midiLow: 50, midiHigh: 68, genre: "Pop", difficulty: 2 },
  { title: "Someone Like You", artist: "Adele", midiLow: 50, midiHigh: 68, genre: "Pop", difficulty: 2 },
  { title: "Take Me to Church", artist: "Hozier", midiLow: 50, midiHigh: 72, genre: "Alternative", difficulty: 2 },
  { title: "Creep", artist: "Radiohead", midiLow: 52, midiHigh: 72, genre: "Alternative", difficulty: 2 },
  { title: "Bohemian Rhapsody", artist: "Queen", midiLow: 48, midiHigh: 76, genre: "Rock", difficulty: 3 },
  { title: "Somebody to Love", artist: "Queen", midiLow: 50, midiHigh: 74, genre: "Rock", difficulty: 3 },
  { title: "Don't Stop Me Now", artist: "Queen", midiLow: 52, midiHigh: 74, genre: "Rock", difficulty: 3 },
  { title: "Under Pressure", artist: "Queen & David Bowie", midiLow: 50, midiHigh: 74, genre: "Rock", difficulty: 3 },
  { title: "Space Oddity", artist: "David Bowie", midiLow: 50, midiHigh: 70, genre: "Rock", difficulty: 2 },
  { title: "Heroes", artist: "David Bowie", midiLow: 48, midiHigh: 68, genre: "Rock", difficulty: 2 },
  { title: "Africa", artist: "Toto", midiLow: 50, midiHigh: 69, genre: "Pop", difficulty: 2 },
  { title: "Take on Me", artist: "a-ha", midiLow: 52, midiHigh: 76, genre: "Pop", difficulty: 3 },
  { title: "Livin' on a Prayer", artist: "Bon Jovi", midiLow: 50, midiHigh: 72, genre: "Rock", difficulty: 3 },
  { title: "Sweet Child O' Mine", artist: "Guns N' Roses", midiLow: 52, midiHigh: 72, genre: "Rock", difficulty: 3 },
  { title: "November Rain", artist: "Guns N' Roses", midiLow: 50, midiHigh: 72, genre: "Rock", difficulty: 3 },
  { title: "Stairway to Heaven", artist: "Led Zeppelin", midiLow: 50, midiHigh: 72, genre: "Rock", difficulty: 3 },
  { title: "Dream On", artist: "Aerosmith", midiLow: 50, midiHigh: 74, genre: "Rock", difficulty: 3 },
  { title: "With or Without You", artist: "U2", midiLow: 50, midiHigh: 69, genre: "Rock", difficulty: 2 },
  { title: "Fix You", artist: "Coldplay", midiLow: 50, midiHigh: 69, genre: "Alternative", difficulty: 2 },
  { title: "The Scientist", artist: "Coldplay", midiLow: 52, midiHigh: 67, genre: "Alternative", difficulty: 1 },
  { title: "Yellow", artist: "Coldplay", midiLow: 50, midiHigh: 68, genre: "Alternative", difficulty: 2 },
  { title: "Clocks", artist: "Coldplay", midiLow: 52, midiHigh: 70, genre: "Alternative", difficulty: 2 },
  { title: "Mr. Brightside", artist: "The Killers", midiLow: 54, midiHigh: 71, genre: "Rock", difficulty: 2 },
  { title: "Use Somebody", artist: "Kings of Leon", midiLow: 50, midiHigh: 69, genre: "Rock", difficulty: 2 },
  { title: "All of Me", artist: "John Legend", midiLow: 52, midiHigh: 69, genre: "Pop", difficulty: 2 },
  { title: "Stay With Me", artist: "Sam Smith", midiLow: 52, midiHigh: 70, genre: "Pop", difficulty: 2 },
  { title: "Say Something", artist: "A Great Big World", midiLow: 52, midiHigh: 72, genre: "Pop", difficulty: 2 },
  { title: "Shallow", artist: "Lady Gaga & Bradley Cooper", midiLow: 50, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "A Thousand Years", artist: "Christina Perri", midiLow: 52, midiHigh: 69, genre: "Pop", difficulty: 1 },
  { title: "Viva la Vida", artist: "Coldplay", midiLow: 53, midiHigh: 69, genre: "Alternative", difficulty: 2 },
  { title: "Chasing Cars", artist: "Snow Patrol", midiLow: 52, midiHigh: 67, genre: "Alternative", difficulty: 1 },
  { title: "Iris", artist: "Goo Goo Dolls", midiLow: 50, midiHigh: 70, genre: "Rock", difficulty: 2 },
  { title: "Hey There Delilah", artist: "Plain White T's", midiLow: 50, midiHigh: 66, genre: "Pop", difficulty: 1 },
  { title: "You Are My Sunshine", artist: "Traditional", midiLow: 50, midiHigh: 64, genre: "Folk", difficulty: 1 },
  { title: "Amazing Grace", artist: "Traditional", midiLow: 50, midiHigh: 64, genre: "Hymn", difficulty: 1 },
  { title: "Danny Boy", artist: "Traditional", midiLow: 48, midiHigh: 67, genre: "Folk", difficulty: 2 },
  { title: "Lean on Me", artist: "Bill Withers", midiLow: 50, midiHigh: 66, genre: "Soul", difficulty: 1 },
  { title: "Ain't No Sunshine", artist: "Bill Withers", midiLow: 50, midiHigh: 65, genre: "Soul", difficulty: 1 },
  { title: "Shallow", artist: "Bradley Cooper version", midiLow: 48, midiHigh: 67, genre: "Pop", difficulty: 2 },
  { title: "Let Her Go", artist: "Passenger", midiLow: 50, midiHigh: 68, genre: "Folk", difficulty: 2 },
  { title: "Photograph", artist: "Ed Sheeran", midiLow: 50, midiHigh: 68, genre: "Pop", difficulty: 2 },
  { title: "Castle on the Hill", artist: "Ed Sheeran", midiLow: 50, midiHigh: 69, genre: "Pop", difficulty: 2 },

  // ── ALTO / LOW MEZZO (bottom ~F3–F5) ────────────────────────────────────
  { title: "Jolene", artist: "Dolly Parton", midiLow: 55, midiHigh: 74, genre: "Country", difficulty: 2 },
  { title: "Rolling in the Deep", artist: "Adele", midiLow: 53, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "Set Fire to the Rain", artist: "Adele", midiLow: 53, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "Hello", artist: "Adele", midiLow: 53, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "Easy on Me", artist: "Adele", midiLow: 52, midiHigh: 72, genre: "Pop", difficulty: 2 },
  { title: "Skyfall", artist: "Adele", midiLow: 53, midiHigh: 72, genre: "Pop", difficulty: 2 },
  { title: "Back to Black", artist: "Amy Winehouse", midiLow: 53, midiHigh: 70, genre: "Soul", difficulty: 2 },
  { title: "Valerie", artist: "Amy Winehouse", midiLow: 55, midiHigh: 72, genre: "Soul", difficulty: 2 },
  { title: "Rehab", artist: "Amy Winehouse", midiLow: 55, midiHigh: 72, genre: "Soul", difficulty: 2 },
  { title: "At Last", artist: "Etta James", midiLow: 53, midiHigh: 72, genre: "Jazz", difficulty: 2 },
  { title: "Summertime", artist: "Ella Fitzgerald", midiLow: 53, midiHigh: 72, genre: "Jazz", difficulty: 2 },
  { title: "Respect", artist: "Aretha Franklin", midiLow: 55, midiHigh: 74, genre: "Soul", difficulty: 2 },
  { title: "Natural Woman", artist: "Aretha Franklin", midiLow: 53, midiHigh: 74, genre: "Soul", difficulty: 2 },
  { title: "Put Your Records On", artist: "Corinne Bailey Rae", midiLow: 55, midiHigh: 72, genre: "Pop", difficulty: 1 },
  { title: "Zombie", artist: "The Cranberries", midiLow: 55, midiHigh: 74, genre: "Rock", difficulty: 2 },
  { title: "Dreams", artist: "Fleetwood Mac", midiLow: 55, midiHigh: 72, genre: "Rock", difficulty: 1 },
  { title: "Landslide", artist: "Fleetwood Mac", midiLow: 53, midiHigh: 69, genre: "Rock", difficulty: 1 },
  { title: "Everywhere", artist: "Fleetwood Mac", midiLow: 55, midiHigh: 72, genre: "Pop", difficulty: 1 },
  { title: "Son of a Preacher Man", artist: "Dusty Springfield", midiLow: 55, midiHigh: 72, genre: "Soul", difficulty: 2 },
  { title: "Make You Feel My Love", artist: "Adele", midiLow: 52, midiHigh: 69, genre: "Pop", difficulty: 1 },
  { title: "Skinny Love", artist: "Bon Iver", midiLow: 55, midiHigh: 72, genre: "Folk", difficulty: 2 },
  { title: "Video Games", artist: "Lana Del Rey", midiLow: 53, midiHigh: 70, genre: "Pop", difficulty: 1 },
  { title: "Summertime Sadness", artist: "Lana Del Rey", midiLow: 55, midiHigh: 72, genre: "Pop", difficulty: 2 },
  { title: "Torn", artist: "Natalie Imbruglia", midiLow: 55, midiHigh: 72, genre: "Pop", difficulty: 2 },
  { title: "Killing Me Softly", artist: "Fugees / Roberta Flack", midiLow: 53, midiHigh: 72, genre: "Soul", difficulty: 2 },
  { title: "Creep", artist: "TLC", midiLow: 55, midiHigh: 72, genre: "R&B", difficulty: 2 },
  { title: "No Scrubs", artist: "TLC", midiLow: 55, midiHigh: 74, genre: "R&B", difficulty: 2 },
  { title: "Crazy in Love", artist: "Beyoncé", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "If I Ain't Got You", artist: "Alicia Keys", midiLow: 53, midiHigh: 74, genre: "R&B", difficulty: 2 },
  { title: "Unwritten", artist: "Natasha Bedingfield", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 2 },

  // ── MEZZO-SOPRANO (bottom ~A3–A5) ───────────────────────────────────────
  { title: "Wrecking Ball", artist: "Miley Cyrus", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Flowers", artist: "Miley Cyrus", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 1 },
  { title: "I Will Always Love You", artist: "Whitney Houston", midiLow: 52, midiHigh: 77, genre: "Pop", difficulty: 3 },
  { title: "Greatest Love of All", artist: "Whitney Houston", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 3 },
  { title: "I Wanna Dance with Somebody", artist: "Whitney Houston", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 3 },
  { title: "Halo", artist: "Beyoncé", midiLow: 55, midiHigh: 79, genre: "Pop", difficulty: 2 },
  { title: "Listen", artist: "Beyoncé", midiLow: 55, midiHigh: 79, genre: "Pop", difficulty: 3 },
  { title: "Love on Top", artist: "Beyoncé", midiLow: 57, midiHigh: 81, genre: "Pop", difficulty: 3 },
  { title: "Just Dance", artist: "Lady Gaga", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 1 },
  { title: "Poker Face", artist: "Lady Gaga", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "Born This Way", artist: "Lady Gaga", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Shallow", artist: "Lady Gaga version", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Since U Been Gone", artist: "Kelly Clarkson", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Stronger", artist: "Kelly Clarkson", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Fighter", artist: "Christina Aguilera", midiLow: 55, midiHigh: 79, genre: "Pop", difficulty: 3 },
  { title: "Beautiful", artist: "Christina Aguilera", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Don't Speak", artist: "No Doubt", midiLow: 55, midiHigh: 74, genre: "Rock", difficulty: 2 },
  { title: "Just a Girl", artist: "No Doubt", midiLow: 55, midiHigh: 77, genre: "Rock", difficulty: 2 },
  { title: "You Oughta Know", artist: "Alanis Morissette", midiLow: 55, midiHigh: 77, genre: "Rock", difficulty: 2 },
  { title: "Total Eclipse of the Heart", artist: "Bonnie Tyler", midiLow: 53, midiHigh: 77, genre: "Pop", difficulty: 3 },
  { title: "I Will Survive", artist: "Gloria Gaynor", midiLow: 55, midiHigh: 74, genre: "Disco", difficulty: 2 },
  { title: "Wannabe", artist: "Spice Girls", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 1 },
  { title: "Titanium", artist: "David Guetta ft. Sia", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Brave", artist: "Sara Bareilles", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "Love Story", artist: "Taylor Swift", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 1 },
  { title: "Shake It Off", artist: "Taylor Swift", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 1 },
  { title: "Blank Space", artist: "Taylor Swift", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 2 },
  { title: "Anti-Hero", artist: "Taylor Swift", midiLow: 55, midiHigh: 72, genre: "Pop", difficulty: 1 },
  { title: "Cruel Summer", artist: "Taylor Swift", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Espresso", artist: "Sabrina Carpenter", midiLow: 55, midiHigh: 74, genre: "Pop", difficulty: 1 },

  // ── SOPRANO (bottom ~C4–C6) ─────────────────────────────────────────────
  { title: "Chandelier", artist: "Sia", midiLow: 55, midiHigh: 79, genre: "Pop", difficulty: 3 },
  { title: "Elastic Heart", artist: "Sia", midiLow: 55, midiHigh: 77, genre: "Pop", difficulty: 3 },
  { title: "No Tears Left to Cry", artist: "Ariana Grande", midiLow: 58, midiHigh: 80, genre: "Pop", difficulty: 3 },
  { title: "thank u, next", artist: "Ariana Grande", midiLow: 57, midiHigh: 79, genre: "Pop", difficulty: 2 },
  { title: "7 rings", artist: "Ariana Grande", midiLow: 57, midiHigh: 77, genre: "Pop", difficulty: 2 },
  { title: "Into You", artist: "Ariana Grande", midiLow: 58, midiHigh: 81, genre: "Pop", difficulty: 3 },
  { title: "Vision of Love", artist: "Mariah Carey", midiLow: 55, midiHigh: 82, genre: "Pop", difficulty: 3 },
  { title: "Hero", artist: "Mariah Carey", midiLow: 55, midiHigh: 79, genre: "Pop", difficulty: 3 },
  { title: "Emotions", artist: "Mariah Carey", midiLow: 55, midiHigh: 84, genre: "Pop", difficulty: 3 },
  { title: "Part of Your World", artist: "The Little Mermaid", midiLow: 57, midiHigh: 77, genre: "Musical Theater", difficulty: 2 },
  { title: "Defying Gravity", artist: "Wicked", midiLow: 57, midiHigh: 81, genre: "Musical Theater", difficulty: 3 },
  { title: "Let It Go", artist: "Frozen", midiLow: 55, midiHigh: 79, genre: "Musical Theater", difficulty: 3 },
  { title: "On My Own", artist: "Les Misérables", midiLow: 55, midiHigh: 77, genre: "Musical Theater", difficulty: 2 },
  { title: "Memory", artist: "Cats", midiLow: 55, midiHigh: 77, genre: "Musical Theater", difficulty: 2 },
  { title: "Think of Me", artist: "Phantom of the Opera", midiLow: 57, midiHigh: 82, genre: "Musical Theater", difficulty: 3 },
  { title: "Don't Rain on My Parade", artist: "Funny Girl", midiLow: 55, midiHigh: 79, genre: "Musical Theater", difficulty: 3 },
];

export default SONG_DATABASE;

/**
 * All unique genres in the database, sorted alphabetically.
 */
export const ALL_GENRES = [...new Set(SONG_DATABASE.map((s) => s.genre))].sort();

/**
 * Difficulty labels.
 */
export const DIFFICULTY_LABELS = {
  1: "Beginner",
  2: "Intermediate",
  3: "Advanced",
};
